---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by DELL.
--- DateTime: 2023-4-27 15:04:21
---
my_module = {}
my_module.constant = "this is a constant"
function my_module.function1()
    print('this is function1\n')
end
local function func2()
    print('this is private function')
end
function my_module.func3()
    func2()
end
return my_module