import time

import scrapy

from test01.items import PoemQuoteCategoryItem, PoemQuoteItem


class PoemQuoteSpider(scrapy.Spider):
    name = 'poem_quote'
    allowed_domains = ['gushicimingju.com']
    start_urls = ['https://www.gushicimingju.com']

    # rules = (
    #     Rule(LinkExtractor(allow=r'.*'), callback='parse_item', follow=True),
    # )
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'Accept-Language': 'zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6',
        'sec-ch-ua': 'Microsoft Edge";v="113", "Chromium";v="113", "Not-A.Brand";v="24',
        'Host': 'www.gushicimingju.com',
        'Referer': 'https://www.gushicimingju.com/',
        'Accept-Encoding:': 'gzip, deflate, br',
        'Content-Type': 'text/html; charset=UTF-8'
    }
    # 远程地址: 127.0.0.1:10809  如果浏览器可以正常访问，scrapy被禁止提示拒绝连接时（ip被禁），这时需要ip代理
    # 通过vpn代理，还可以打开该网址，在将浏览器访问该网址，按F12调出浏览器开发工具，找到网络下：远程地址: 127.0.0.1:10809
    # 将远程地址设置为代理ip既可以绕过ip封锁
    proxy_ip = '127.0.0.1'
    proxy_port = '10809'
    proxy_url = f'https://{proxy_ip}:{proxy_port}'

    def start_requests(self):
        urls = ['/shiju/chuntian/', '/shiju/chongyangjie/', '/shiju/laoshi/', '/shiju/juhua/', '/shiju/libie/',
                '/shiju/xiatian/', '/shiju/sinian/', '/shiju/hehua/', '/shiju/taiyang/', '/shiju/qiutian/',
                '/shiju/xiangsi/', '/shiju/yueliang/', '/shiju/aiqing/', '/shiju/youqing/', '/shiju/fengci/',
                '/shiju/dongtian/', '/shiju/xue/', '/shiju/weimeishiju/', '/shiju/duanwujie/', '/shiju/qixi/',
                '/shiju/zhongqiujie/', '/shiju/changjiang/', '/shiju/ma/', '/shiju/hua/', '/shiju/taishan/',
                '/shiju/caoyuan/', '/shiju/aiguo/', '/shiju/shijian/', '/shiju/meihua/', '/shiju/huanghe/',
                '/shiju/dushu/', '/shiju/qiuyu/', '/shiju/xihu/', '/shiju/sixiang/', '/shiju/xingxing/',
                '/shiju/zhanzheng/', '/shiju/chuncao/', '/shiju/qiantangjiangdachao/', '/shiju/huangshan/',
                '/shiju/yu/', '/shiju/lizhi/', '/shiju/chunyu/', '/shiju/cha/', '/shiju/muai/', '/shiju/jiu/',
                '/shiju/lushan/', '/shiju/chunjie/', '/shiju/xuexi/', '/shiju/guilinshanshui/', '/shiju/qinqing/',
                '/shiju/shan/', '/shiju/liqiu/', '/shiju/meinv/', '/shiju/zhuzi/', '/shiju/zheli/', '/shiju/dahai/',
                '/shiju/shanggan/', '/shiju/dongzhi/', '/shiju/songbie/', '/shiju/pubu/', '/shiju/yuanxiaojie/',
                '/shiju/guihua/', '/shiju/changcheng/', '/shiju/taohua/', '/shiju/baidicheng/', '/shiju/xiyang/',
                '/shiju/huanghelou/', '/shiju/qingmingjie/', '/shiju/xiejing/', '/shiju/chunfeng/', '/shiju/songshu/',
                '/shiju/sanxia/', '/shiju/lanhua/', '/shiju/hanshi/', '/shiju/dongtinghu/', '/shiju/meinanzi/',
                '/shiju/chuan/', '/shiju/lichun/', '/shiju/bailu/', '/shiju/xuehua/', '/shiju/qiuyue/',
                '/shiju/chunhua/', '/shiju/xinghua/', '/shiju/lidong/', '/shiju/hanlu/', '/shiju/daxue/',
                '/shiju/shamo/', '/shiju/liuxu/', '/shiju/lihua/', '/shiju/qiufen/', '/shiju/shuangjiang/',
                '/shiju/xiaoxue/', '/shiju/zongzi/', '/shiju/fengye/', '/shiju/shuqing/', '/shiju/chunfen/',
                '/shiju/mudan/', '/shiju/chushu/', '/shiju/liushui/', '/shiju/duoqing/', '/shiju/chunpan/',
                '/shiju/shanshui/', '/shiju/bingzhu/', '/shiju/chaimen/', '/shiju/yun/', '/shiju/fusheng/',
                '/shiju/yixiang/', '/shiju/niao/', '/shiju/dansha/', '/shiju/fengguang/', '/shiju/fuqin/',
                '/shiju/yingwu/', '/shiju/fumu/', '/shiju/mifeng/', '/shiju/dayan/', '/shiju/qiufeng/',
                '/shiju/xiongxinzhuangzhi/', '/shiju/rensheng/', '/shiju/jingzhe/', '/shiju/guyu/', '/shiju/lixia/',
                '/shiju/xiaoman/', '/shiju/mangzhong/', '/shiju/xiazhi/', '/shiju/qiuqian/', '/shiju/luhua/',
                '/shiju/yingxiong/', '/shiju/meiyu/', '/shiju/youcaihua/', '/shiju/jiashu/', '/shiju/youzi/',
                '/shiju/jinqian/', '/shiju/weirenchushi/', '/shiju/douji/', '/shiju/kucai/', '/shiju/huaelou/',
                '/shiju/huanggua/', '/shiju/chuncai/', '/shiju/shengcai/', '/shiju/zhusun/', '/shiju/jiucai/',
                '/shiju/xiangfeng/', '/shiju/gongming/', '/shiju/shiwu/', '/shiju/guxiang/', '/shiju/zhiyin/',
                '/shiju/xueming/', '/shiju/guren/', '/shiju/fuyun/', '/shiju/daowang/', '/shiju/hongye/',
                '/shiju/ziyou/', '/shiju/xiaqi/', '/shiju/luoye/', '/shiju/xifeng/', '/shiju/dongfeng/',
                '/shiju/nanfeng/', '/shiju/beifeng/', '/shiju/xiangrikui/', '/shiju/wutong/', '/shiju/pipa/',
                '/shiju/shenghuo/', '/shiju/jiaren/', '/shiju/mingli/', '/shiju/changan/', '/shiju/fengyu/',
                '/shiju/fugui/', '/shiju/luopo/', '/shiju/xinxiong/', '/shiju/qingshan/', '/shiju/wangshi/',
                '/shiju/fengliu/', '/shiju/liunian/', '/shiju/yecao/', '/shiju/zhaolu/', '/shiju/huanghun/',
                '/shiju/riluo/', '/shiju/pinjian/', '/shiju/qingfeng/', '/shiju/lichou/', '/shiju/enyuan/',
                '/shiju/nanguo/', '/shiju/dalei/', '/shiju/cu/', '/shiju/yan/', '/shiju/baifa/', '/shiju/cangsheng/',
                '/shiju/meiren/', '/shiju/xihe/', '/shiju/wanxia/', '/shiju/change/', '/shiju/tuzi/', '/shiju/xinku/',
                '/shiju/gaolou/', '/shiju/denggao/', '/shiju/yuanyang/', '/shiju/chunri/', '/shiju/muchun/',
                '/shiju/jiangjun/', '/shiju/jingmen/', '/shiju/wuxia/', '/shiju/rimu/', '/shiju/shenshan/',
                '/shiju/weiqi/', '/shiju/qingguoqingcheng/', '/shiju/penglai/', '/shiju/wenzhang/', '/shiju/cimu/',
                '/shiju/zhougong/', '/shiju/xinyue/', '/shiju/haiou/', '/shiju/chanyu/', '/shiju/hanjia/',
                '/shiju/tianzi/', '/shiju/heqin/', '/shiju/yishang/', '/shiju/chunshui/', '/shiju/qingqiu/',
                '/shiju/beiqiu/', '/shiju/qiliang/', '/shiju/huainan/', '/shiju/maizi/', '/shiju/zao/',
                '/shiju/zaohua/', '/shiju/baoen/', '/shiju/baoguo/', '/shiju/shane/', '/shiju/yumenguan/',
                '/shiju/youxiaer/', '/shiju/doukou/', '/shiju/jiguan/', '/shiju/lvdou/', '/shiju/hulu/',
                '/shiju/xinshi/', '/shiju/hongchen/', '/shiju/fengnian/', '/shiju/lisao/', '/shiju/chuncheng/',
                '/shiju/duanchang/', '/shiju/boqing/', '/shiju/dongfang/', '/shiju/fangxin/', '/shiju/guangyin/',
                '/shiju/qiaocui/', '/shiju/chouchang/', '/shiju/taxiang/', '/shiju/chunmeng/', '/shiju/hongzhu/',
                '/shiju/yuexia/', '/shiju/yangguan/', '/shiju/beiliang/', '/shiju/jiubie/', '/shiju/dengshan/',
                '/shiju/qilin/', '/shiju/zheyao/', '/shiju/huanghua/', '/shiju/liba/', '/shiju/boxing/', '/shiju/buyi/',
                '/shiju/qiuse/', '/shiju/fengyue/', '/shiju/fuming/', '/shiju/zhegu/', '/shiju/hao/', '/shiju/mingyue/',
                '/shiju/xingwang/', '/shiju/suiyue/', '/shiju/jiangshan/', '/shiju/zhongyuan/', '/shiju/qinhuai/',
                '/shiju/qianchao/', '/shiju/liangchen/', '/shiju/lingzhi/', '/shiju/fushi/', '/shiju/liuxue/',
                '/shiju/houtinghua/', '/shiju/yinyang/', '/shiju/zhaoxia/', '/shiju/shaonian/', '/shiju/chunguang/',
                '/shiju/shousui/', '/shiju/gesheng/', '/shiju/jiangnan/', '/shiju/chanjuan/', '/shiju/qiangdi/',
                '/shiju/xiaotiao/', '/shiju/wuqing/', '/shiju/lishan/', '/shiju/gongzhu/', '/shiju/jimo/',
                '/shiju/yanghua/', '/shiju/youqing1/', '/shiju/wanli/', '/shiju/jiangdong/', '/shiju/shaoguang/',
                '/shiju/yehua/', '/shiju/shengxian/', '/shiju/huakai/', '/shiju/hualuo/', '/shiju/sangeng/',
                '/shiju/wugeng/', '/shiju/shangxin/', '/shiju/bajiao/', '/shiju/xiefeng/', '/shiju/xiyu/',
                '/shiju/liusu/', '/shiju/tianliang/', '/shiju/wulingren/', '/shiju/xunmei/', '/shiju/tianyuan/',
                '/shiju/huangjin/', '/shiju/qiuri/', '/shiju/richu/', '/shiju/donghai/', '/shiju/nanhai/',
                '/shiju/tianya/', '/shiju/haijiao/', '/shiju/tianyahaijiao/', '/shiju/boyaziqi/', '/shiju/quanshi/',
                '/shiju/huangye/', '/shiju/lvye/', '/shiju/junzi/', '/shiju/xiaoren/', '/shiju/baixue/',
                '/shiju/fenfang/', '/shiju/chicha/', '/shiju/xiongnu/', '/shiju/xinruzhishui/', '/shiju/xianbei/',
                '/shiju/xingming/', '/shiju/wenren/', '/shiju/yiyue/', '/shiju/eryue/', '/shiju/sanyue/',
                '/shiju/siyue/', '/shiju/wuyue/', '/shiju/liuyue/', '/shiju/qiyue/', '/shiju/bayue/', '/shiju/jiuyue/',
                '/shiju/shiyue/', '/shiju/shiyiyue/', '/shiju/shieryue/', '/shiju/layue/', '/shiju/mengli/',
                '/shiju/xiaoxiao/', '/shiju/canyue/', '/shiju/yangliu/', '/shiju/tumi/', '/shiju/xiyan/',
                '/shiju/zhenxian/', '/shiju/yulin/', '/shiju/pangbo/', '/shiju/yingtao/', '/shiju/xingan/',
                '/shiju/taiji/', '/shiju/cangqiong/', '/shiju/zhongcheng/', '/shiju/baishou/', '/shiju/riyue/',
                '/shiju/chusai/', '/shiju/rusai/', '/shiju/youyou/', '/shiju/jianghu/', '/shiju/yanzi/',
                '/shiju/sangang/', '/shiju/daoyi/', '/shiju/wanfeng/', '/shiju/nandou/', '/shiju/beidou/',
                '/shiju/chunse/', '/shiju/sun/', '/shiju/chunsun/', '/shiju/jielu/', '/shiju/shuguo/', '/shiju/nvzi/',
                '/shiju/guilai/', '/shiju/yiyan/', '/shiju/bolan/', '/shiju/zhifen/', '/shiju/yanse/', '/shiju/jiujiu/',
                '/shiju/chunxiao/', '/shiju/shengming/', '/shiju/langzi/', '/shiju/zhuyan/', '/shiju/xudu/',
                '/shiju/zhuangshi/', '/shiju/tieqi/', '/shiju/buping/', '/shiju/fenghuo/', '/shiju/xinsui/',
                '/shiju/hongzhuang/', '/shiju/shediao/', '/shiju/shuijing/', '/shiju/liuli/', '/shiju/xianren/',
                '/shiju/gongfu/', '/shiju/maolu/', '/shiju/dongpo/', '/shiju/xizi/', '/shiju/shennv/',
                '/shiju/longtou/', '/shiju/zhaomu/', '/shiju/deng/', '/shiju/luohua/', '/shiju/zhanguo/',
                '/shiju/aiyuan/', '/shiju/langya/', '/shiju/nanshan/', '/shiju/qianqiu/', '/shiju/qingchun/',
                '/shiju/zhuangzhou/', '/shiju/蝴蝶/', '/shiju/zhiqi/', '/shiju/chan/', '/shiju/qingtian/',
                '/shiju/taoli/', '/shiju/xianyang/', '/shiju/xiaopin/', '/shiju/feishuang/', '/shiju/shidao/',
                '/shiju/chuguo/', '/shiju/tulao/', '/shiju/gujin/', '/shiju/xinren/', '/shiju/jiuren/',
                '/shiju/yueluo/', '/shiju/doujiu/', '/shiju/liulei/', '/shiju/wushan/', '/shiju/huangyin/',
                '/shiju/tanxi/', '/shiju/xibei/', '/shiju/xianren2/', '/shiju/baiyu/', '/shiju/liuxing/',
                '/shiju/heshou/', '/shiju/furong/', '/shiju/bailu2/', '/shiju/qingsong/', '/shiju/hongyan/',
                '/shiju/fenshou/', '/shiju/qianli/', '/shiju/cangcang/', '/shiju/yanwu/', '/shiju/lvluo/',
                '/shiju/baizhi/', '/shiju/caomu/', '/shiju/chenggong/', '/shiju/qingchen/', '/shiju/piaopiao/',
                '/shiju/gongnv/', '/shiju/emei/', '/shiju/xiaoxiang/', '/shiju/qiulu/', '/shiju/zhizu/',
                '/shiju/nishang/', '/shiju/taibai/', '/shiju/titang/', '/shiju/lianyao/', '/shiju/pingyuan/',
                '/shiju/fuchunshan/', '/shiju/haike/', '/shiju/mingxing/', '/shiju/xiucai/', '/shiju/renjian/',
                '/shiju/rouchang/', '/shiju/dingxiang/', '/shiju/fenghuang/', '/shiju/tiandi/', '/shiju/luoyang/',
                '/shiju/zhongsheng/', '/shiju/hongmao/', '/shiju/xiuse/', '/shiju/liyuan/', '/shiju/dengke/',
                '/shiju/hufu/', '/shiju/putao/', '/shiju/shengren/', '/shiju/yunyu/', '/shiju/jinling/',
                '/shiju/huanxi/', '/shiju/fengyun/', '/shiju/menghu/', '/shiju/liehuo/', '/shiju/baigu/',
                '/shiju/yeshen/', '/shiju/qingquan/', '/shiju/taoyuan/', '/shiju/qingfeng1/', '/shiju/weiyu/',
                '/shiju/feihong/', '/shiju/yangchun/', '/shiju/fangcao/', '/shiju/qiqi/', '/shiju/huangli/',
                '/shiju/xieyang/', '/shiju/hanya/', '/shiju/xiaohun/', '/shiju/xiangnang/', '/shiju/denghuo/',
                '/shiju/zhouyu/', '/shiju/lvshui/', '/shiju/yuqian/', '/shiju/zhumen/', '/shiju/pipa1/',
                '/shiju/chunhan/', '/shiju/huamei/', '/shiju/zhengzhan/', '/shiju/jiaolong/', '/shiju/xuanyuan/',
                '/shiju/zhinv/', '/shiju/yuweng/', '/shiju/housheng/', '/shiju/feicui/', '/shiju/jingyu/',
                '/shiju/bihai/', '/shiju/leisheng/', '/shiju/huangying/', '/shiju/fengzheng/', '/shiju/qingshen/',
                '/shiju/shitou/', '/shiju/yinhe/', '/shiju/shachuang/', '/shiju/naner/', '/shiju/ernv/',
                '/shiju/longmen/', '/shiju/mengxiang/', '/shiju/luori/', '/shiju/changhe/', '/shiju/shenxian/',
                '/shiju/wangyou/', '/shiju/xuancao/', '/shiju/shanchuan/', '/shiju/youren/', '/shiju/gange/',
                '/shiju/longshe/', '/shiju/gurou/', '/shiju/yiguan/', '/shiju/qiushui/', '/shiju/shusheng/',
                '/shiju/bainian/', '/shiju/zhongchen/', '/shiju/hongqi/', '/shiju/canghai/', '/shiju/fuyang/',
                '/shiju/kangkai/', '/shiju/lingyun/', '/shiju/zhuangzhi/', '/shiju/guanshan/', '/shiju/jian/',
                '/shiju/yuzhou/', '/shiju/shijie/', '/shiju/shaohua/', '/shiju/chunjiang/', '/shiju/shachang/',
                '/shiju/guyuan/', '/shiju/min/', '/shiju/qianlanghoulang/', '/shiju/caiyun/', '/shiju/zhangfu/',
                '/shiju/kunlun/', '/shiju/xuyanya/', '/shiju/baihua/', '/shiju/shijie1/', '/shiju/geming/',
                '/shiju/daoshi/', '/shiju/lihen/', '/shiju/biehen/', '/shiju/ertong/', '/shiju/xunchun/',
                '/shiju/mangmang/', '/shiju/guaizhang/', '/shiju/haojie/', '/shiju/lazhu/', '/shiju/chunwan/',
                '/shiju/ying/', '/shiju/meng/', '/shiju/yanyu/', '/shiju/jinghua/', '/shiju/tiaotiao/',
                '/shiju/xiaohun2/', '/shiju/yanbo/', '/shiju/qujiang/', '/shiju/qinguan/', '/shiju/qinglu/',
                '/shiju/yufu/', '/shiju/momo/', '/shiju/duijiu/', '/shiju/qiuye/', '/shiju/fuyi/', '/shiju/huanjiao/',
                '/shiju/chungui/', '/shiju/songhua/', '/shiju/mingri/', '/shiju/denghua/', '/shiju/yanzhi/',
                '/shiju/kelian/', '/shiju/qingqing/', '/shiju/zanhua/', '/shiju/jiuxing/', '/shiju/shizi/',
                '/shiju/qiqi1/', '/shiju/sisi/', '/shiju/suisui/', '/shiju/kezhong/', '/shiju/tanzhi/', '/shiju/momo1/',
                '/shiju/gumian/', '/shiju/luoqun/', '/shiju/mingdeng/', '/shiju/shangshen/', '/shiju/yaoyao/',
                '/shiju/jiurou/', '/shiju/huangchong/', '/shiju/hundun/', '/shiju/kuxin/', '/shiju/tiansheng/',
                '/shiju/zhengrong/', '/shiju/jiangshui/', '/shiju/yangzhou/', '/shiju/shanji/', '/shiju/diao/',
                '/shiju/bailu3/', '/shiju/cailing/', '/shiju/yueming/', '/shiju/luyu/', '/shiju/huangquan/',
                '/shiju/gujiu/', '/shiju/yinshan/', '/shiju/gushu/', '/shiju/qiubo/', '/shiju/haise/',
                '/shiju/qingyun/', '/shiju/bole/', '/shiju/jiyu/', '/shiju/shennong/', '/shiju/shanlin/',
                '/shiju/yingying/', '/shiju/gewu/', '/shiju/xinzhuang/', '/shiju/bianzi/', '/shiju/songren/',
                '/shiju/qingtai/', '/shiju/duihua/', '/shiju/jiali/', '/shiju/yiyi/', '/shiju/congcong/',
                '/shiju/fenxiang/', '/shiju/guguo/', '/shiju/mochou/', '/shiju/liuguang/', '/shiju/genggeng/',
                '/shiju/xiangshi/', '/shiju/shijian1/', '/shiju/chunshan/', '/shiju/dizi/', '/shiju/cuiliu/',
                '/shiju/chuang/', '/shiju/shengxiao/', '/shiju/xianyun/', '/shiju/changsheng/', '/shiju/shanhu/',
                '/shiju/pojing/', '/shiju/hunduan/', '/shiju/dujuan/', '/shiju/nianhua/', '/shiju/baiyu1/',
                '/shiju/leiliu/', '/shiju/taotao/', '/shiju/huhu/', '/shiju/zijia/', '/shiju/wuling/',
                '/shiju/chunyou/', '/shiju/hongying/', '/shiju/chahua/', '/shiju/qinglou/', '/shiju/longshui/',
                '/shiju/keai/', '/shiju/fengjing/', '/shiju/liangxiao/', '/shiju/wenrou/', '/shiju/cangmang/',
                '/shiju/wusha/', '/shiju/zhuyu/', '/shiju/shujuan/', '/shiju/pangxie/', '/shiju/puchang/',
                '/shiju/rouqing/', '/shiju/xinqing/', '/shiju/youlan/', '/shiju/lihun/', '/shiju/qiusheng/',
                '/shiju/xingxing1/', '/shiju/wuyan/', '/shiju/wuyu/', '/shiju/chuiliu/', '/shiju/xingren/',
                '/shiju/yuenv/', '/shiju/cailian/', '/shiju/zuiweng/', '/shiju/xibie/', '/shiju/songke/',
                '/shiju/jinwu/', '/shiju/cangbo/', '/shiju/jiliao/', '/shiju/caihong/', '/shiju/qinchuan/',
                '/shiju/yanhua/', '/shiju/xinghan/', '/shiju/shudao/', '/shiju/sensen/', '/shiju/changfeng/',
                '/shiju/jinxiu/', '/shiju/chonglong/', '/shiju/he/', '/shiju/gaotang/', '/shiju/suimu/',
                '/shiju/haidi/', '/shiju/renxin/', '/shiju/xihuan/', '/shiju/fengbo/', '/shiju/yanxia/',
                '/shiju/shengsi/', '/shiju/shishi/', '/shiju/xuewen/', '/shiju/yuanyue/', '/shiju/haitang/',
                '/shiju/shifei/', '/shiju/manman/', '/shiju/diandian/', '/shiju/yaozhi/', '/shiju/fangfei/',
                '/shiju/yujia/', '/shiju/qiaomai/', '/shiju/liuse/', '/shiju/jiji/', '/shiju/nanbei/',
                '/shiju/hongjian/', '/shiju/ziwei/', '/shiju/shanghua/', '/shiju/dandan/', '/shiju/liuyao/',
                '/shiju/rongrong/', '/shiju/nongying/', '/shiju/huacao/', '/shiju/xiangjiang/', '/shiju/taqing/',
                '/shiju/shengge/', '/shiju/fuping/', '/shiju/lingbo/', '/shiju/jinse/', '/shiju/ranran/',
                '/shiju/xianqing/', '/shiju/duanhun/', '/shiju/yuchun/', '/shiju/xichun/', '/shiju/yaoyao1/',
                '/shiju/xinchou/', '/shiju/taoye/', '/shiju/baiping/', '/shiju/huqin/', '/shiju/menglong/',
                '/shiju/quzhong/', '/shiju/huafang/', '/shiju/qiujiang/', '/shiju/qiaomu/', '/shiju/xiaoyu/',
                '/shiju/zhenchu/', '/shiju/zifu/', '/shiju/liulang/', '/shiju/dongjun/', '/shiju/nanpu/',
                '/shiju/niaoniao/', '/shiju/chenchen/', '/shiju/chunchao/', '/shiju/xinlv/', '/shiju/fohua/',
                '/shiju/honglou/', '/shiju/fangxin1/', '/shiju/leihen/', '/shiju/ranchan/', '/shiju/wuxin/',
                '/shiju/wanyi/', '/shiju/siliang/', '/shiju/yansuo/', '/shiju/youli/', '/shiju/ningmou/',
                '/shiju/xiangche/', '/shiju/baoma/', '/shiju/lianlian/', '/shiju/qingshan1/', '/shiju/shutou/',
                '/shiju/hualian/', '/shiju/xinyan/', '/shiju/zaochun/', '/shiju/nianshao/', '/shiju/dangnian/',
                '/shiju/bingsi/', '/shiju/wa/', '/shiju/yanguang/', '/shiju/liuhua/', '/shiju/diankuang/',
                '/shiju/baitou/', '/shiju/baihua1/', '/shiju/honghua/', '/shiju/xixi/', '/shiju/fenfen/',
                '/shiju/sang/', '/shiju/shuijiao/', '/shiju/can/', '/shiju/ersun/', '/shiju/chema/', '/shiju/qingmei/',
                '/shiju/fenglang/', '/shiju/shuidao/', '/shiju/jian1/', '/shiju/huaihua/', '/shiju/wanggui/',
                '/shiju/jiazi/', '/shiju/chuichui/', '/shiju/taihu/', '/shiju/mengmeng/', '/shiju/yu1/',
                '/shiju/banli/', '/shiju/zhujiu/', '/shiju/dihua/', '/shiju/taikong/', '/shiju/dongnan/',
                '/shiju/tianjiang/', '/shiju/tianqian/', '/shiju/jingqi/', '/shiju/saibei/', '/shiju/zhichi/',
                '/shiju/bolang/', '/shiju/liutiao/', '/shiju/qingbo/', '/shiju/meizi/', '/shiju/kanshu/',
                '/shiju/yuese/', '/shiju/qiuguang/', '/shiju/zhizhu/', '/shiju/tiangong/', '/shiju/chunyan/',
                '/shiju/shengya/', '/shiju/cong/', '/shiju/lingluo/', '/shiju/huaqingchi/', '/shiju/yaotiao/',
                '/shiju/liuchun/', '/shiju/mingfei/', '/shiju/junwang/', '/shiju/danqing/', '/shiju/hangong/',
                '/shiju/qingzhong/', '/shiju/shiyi/', '/shiju/fanhua/', '/shiju/rongru/', '/shiju/xinghe/',
                '/shiju/yunv/', '/shiju/xiancao/', '/shiju/bailong/', '/shiju/qiuxing/', '/shiju/feihua/',
                '/shiju/jiefa/', '/shiju/luoyi/', '/shiju/qinghuai/', '/shiju/yinshu/', '/shiju/linglong/',
                '/shiju/nankan/', '/shiju/cangchun/', '/shiju/jiangmei/', '/shiju/danyue/', '/shiju/canchun/',
                '/shiju/tianzhen/', '/shiju/yaorao/', '/shiju/guangjing/', '/shiju/xiangjian/', '/shiju/shaqi/',
                '/shiju/bieli/', '/shiju/yinglie/', '/shiju/tianshan/', '/shiju/kuzhi/', '/shiju/fufeng/',
                '/shiju/kaixin/', '/shiju/sijun/', '/shiju/zhongnanshan/', '/shiju/jiuqu/', '/shiju/wenwu/',
                '/shiju/kuhan/', '/shiju/aiai/', '/shiju/yuyu/', '/shiju/jinshi/', '/shiju/cangtian/', '/shiju/qizi/',
                '/shiju/fuzi/', '/shiju/yumu/', '/shiju/yuyan/', '/shiju/bairi/', '/shiju/yinqin/', '/shiju/dongli/',
                '/shiju/gaojie/', '/shiju/baodao/', '/shiju/chanmian/', '/shiju/yangtai/', '/shiju/silin/',
                '/shiju/kaihua/', '/shiju/ziliuma/', '/shiju/huangyun/', '/shiju/zhongshan/', '/shiju/yunduan/',
                '/shiju/cishi/', '/shiju/jiuhan/', '/shiju/zhiqiu/', '/shiju/longtan/', '/shiju/huae/',
                '/shiju/tianjia/', '/shiju/xiangxie/', '/shiju/zhijiu/', '/shiju/bicao/', '/shiju/nongfu/',
                '/shiju/hanfeng/', '/shiju/qiwu/', '/shiju/yangmei/', '/shiju/shuofeng/', '/shiju/dangyang/',
                '/shiju/wuhu/', '/shiju/leiting/', '/shiju/gumu/', '/shiju/rongma/', '/shiju/leiyu/', '/shiju/wangu/',
                '/shiju/xinqiu/', '/shiju/zhexian/', '/shiju/guishen/', '/shiju/shengming2/', '/shiju/wencai/',
                '/shiju/liuchuan/', '/shiju/longzhou/', '/shiju/chongru/', '/shiju/shijiu/', '/shiju/sishui/',
                '/shiju/bingqi/', '/shiju/yifang/', '/shiju/chuixiao/', '/shiju/shenghuang/', '/shiju/konghou/',
                '/shiju/chuyue/', '/shiju/zhengguang/', '/shiju/wan/', '/shiju/tongguan/', '/shiju/gongdian/',
                '/shiju/jinjia/', '/shiju/fusang/', '/shiju/mingming/', '/shiju/mingzhu/', '/shiju/jinjiang/',
                '/shiju/xiaoyu2/', '/shiju/zaoqiu/', '/shiju/qieqie/', '/shiju/woniu/', '/shiju/bazhen/',
                '/shiju/yiqi/', '/shiju/yishi/', '/shiju/chailang/', '/shiju/xiangcun/', '/shiju/tuanyuan/',
                '/shiju/shenshen/', '/shiju/hongying2/', '/shiju/feifei/', '/shiju/canxue/', '/shiju/leizhu/',
                '/shiju/canglang/', '/shiju/pinghua/', '/shiju/fengshuang/', '/shiju/binghun/', '/shiju/yegui/',
                '/shiju/liantian/', '/shiju/luohong/', '/shiju/fengsheng/', '/shiju/shangliang/', '/shiju/honglu/',
                '/shiju/gongfu2/', '/shiju/pingting/', '/shiju/chuangqian/', '/shiju/huaibao/', '/shiju/chouren/',
                '/shiju/duoshao/', '/shiju/jinye/', '/shiju/xianrenzhang/', '/shiju/juanjuan/', '/shiju/xiaozhou/',
                '/shiju/huansha/', '/shiju/qiumu/', '/shiju/shanlu/', '/shiju/jiqing/', '/shiju/qiuyuan/',
                '/shiju/xiaosa/', '/shiju/xiaosa2/', '/shiju/chichi/', '/shiju/chunjiao/', '/shiju/wumei/',
                '/shiju/jiangying/', '/shiju/piaoling/', '/shiju/bianzhou/', '/shiju/gugong/', '/shiju/xixi2/',
                '/shiju/qingdeng/', '/shiju/shushu/', '/shiju/yuye/', '/shiju/jiyu2/', '/shiju/caibi/',
                '/shiju/xianchou/', '/shiju/chonglai/', '/shiju/bingxiao/', '/shiju/qingying/', '/shiju/yeye/',
                '/shiju/mengzhong/', '/shiju/youmeng/', '/shiju/qingcao/', '/shiju/zhidao/', '/shiju/xiaoshan/',
                '/shiju/xinqing2/', '/shiju/qiushen/', '/shiju/yuhu/', '/shiju/xiangu/', '/shiju/xiongjin/',
                '/shiju/zuori/', '/shiju/pingsheng/', '/shiju/jusan/', '/shiju/shengji/', '/shiju/cuoto/',
                '/shiju/ronghua/', '/shiju/qier/', '/shiju/gufu/', '/shiju/huanxiang/', '/shiju/jinzhao/',
                '/shiju/jiubei/', '/shiju/xiaoxi/', '/shiju/chouchu/', '/shiju/shili/', '/shiju/beifang/',
                '/shiju/guizhi/', '/shiju/qiulan/', '/shiju/jifeng/', '/shiju/pianpian/', '/shiju/sihai/',
                '/shiju/gaoshan/', '/shiju/wangmu/', '/shiju/shumu/', '/shiju/xiaose/', '/shiju/yuanxing/',
                '/shiju/paihuai/', '/shiju/jiujiang/', '/shiju/youyu/', '/shiju/hongyan2/', '/shiju/qiqi2/',
                '/shiju/lili/', '/shiju/beifeng2/', '/shiju/huashan/', '/shiju/sishi/', '/shiju/zongmiao/',
                '/shiju/jide/', '/shiju/liaoliao/', '/shiju/liangfeng/', '/shiju/biyi/', '/shiju/taiping/',
                '/shiju/lifa/', '/shiju/kaijia/', '/shiju/mengshou/', '/shiju/shenlong/', '/shiju/jiushi/',
                '/shiju/diaoyu/', '/shiju/pili/', '/shiju/cunwang/', '/shiju/kexin/', '/shiju/hongxiu/',
                '/shiju/luoxiu/', '/shiju/xiagu/', '/shiju/junchen/', '/shiju/zhangong/', '/shiju/honge/',
                '/shiju/chuijiao/', '/shiju/xuanxuan/', '/shiju/yuanye/', '/shiju/baishui/', '/shiju/jinshi2/',
                '/shiju/jiuri/', '/shiju/nanwang/', '/shiju/yanlei/', '/shiju/polu/', '/shiju/cixiong/',
                '/shiju/handan/', '/shiju/pingyuanjun/', '/shiju/gongzi/', '/shiju/suoqiu/', '/shiju/xinli/',
                '/shiju/muyun/', '/shiju/jiaogong/', '/shiju/jiuzhou/', '/shiju/yinxin/', '/shiju/guren1/',
                '/shiju/posuo/', '/shiju/zhengren/', '/shiju/guiyan/', '/shiju/xiaoyao/', '/shiju/songbai/',
                '/shiju/mutong/', '/shiju/yinyin/', '/shiju/wuye/', '/shiju/longtou1/', '/shiju/beihai/',
                '/shiju/honglian/', '/shiju/shiren/', '/shiju/wugu/', '/shiju/jieyou/', '/shiju/lvyang/',
                '/shiju/leiyan/', '/shiju/chouchang1/', '/shiju/chichu/', '/shiju/ziwei1/', '/shiju/huibi/',
                '/shiju/meijian/', '/shiju/xinshang/', '/shiju/baisui/', '/shiju/qianjin/', '/shiju/qiansui/',
                '/shiju/wansui/', '/shiju/canhong/', '/shiju/nanyuan/', '/shiju/huantang/', '/shiju/yanbo1/',
                '/shiju/tianqi/', '/shiju/louhua/', '/shiju/meishan/', '/shiju/baochou/', '/shiju/yinjiu/',
                '/shiju/tianjiao/', '/shiju/mijin/', '/shiju/yunwu/', '/shiju/shenzhou/', '/shiju/gungun/',
                '/shiju/huairen/', '/shiju/chunyi/', '/shiju/renqing/', '/shiju/dongjia/', '/shiju/fulao/',
                '/shiju/yushui/', '/shiju/jingshen/', '/shiju/maijiu/', '/shiju/huafa/', '/shiju/dashu/',
                '/shiju/zhengyi/', '/shiju/yuxia/', '/shiju/shuxing/', '/shiju/songzhu/', '/shiju/wanshi/',
                '/shiju/baijiu/', '/shiju/tuantuan/', '/shiju/xiansheng/', '/shiju/laobing/', '/shiju/jilv/',
                '/shiju/qinyou/', '/shiju/bingma/', '/shiju/mati/', '/shiju/luci/', '/shiju/yueyuan/',
                '/shiju/cangshan/', '/shiju/fanzhou/', '/shiju/wuchang/', '/shiju/hehan/', '/shiju/xingchen/',
                '/shiju/guanghui/', '/shiju/tianxia/', '/shiju/yulu/', '/shiju/dadao/', '/shiju/weishui/',
                '/shiju/chanchan/', '/shiju/bailian/', '/shiju/xunhua/', '/shiju/maihua/', '/shiju/niannian/',
                '/shiju/hualin/', '/shiju/yicun/', '/shiju/tianbei/', '/shiju/ganhan/', '/shiju/xinxin/',
                '/shiju/xixi1/', '/shiju/juju/', '/shiju/guqiu/', '/shiju/xinyu/', '/shiju/gaoren/', '/shiju/lizhi1/',
                '/shiju/yelao/', '/shiju/guanxin/', '/shiju/dongjing/', '/shiju/kongtong/', '/shiju/huishou/',
                '/shiju/wangliang/', '/shiju/mangran/', '/shiju/geli/', '/shiju/chuncai1/', '/shiju/banlv/',
                '/shiju/bianshui/', '/shiju/she/', '/shiju/wulai/', '/shiju/zhanchang/', '/shiju/shexiang/',
                '/shiju/kongque/', '/shiju/zhuque/', '/shiju/huaxie/', '/shiju/chunxue/', '/shiju/xingle/',
                '/shiju/lvtai/', '/shiju/shuanglong/', '/shiju/zhouye/', '/shiju/haishang/', '/shiju/liangtian/',
                '/shiju/wanzhuang/', '/shiju/tianshang/', '/shiju/yinhan/', '/shiju/leidian/', '/shiju/zhichuang/',
                '/shiju/jinsheng/', '/shiju/wanshuiqianshan/', '/shiju/shangchun/', '/shiju/yanyan/', '/shiju/zaowan/',
                '/shiju/qingbin/', '/shiju/changqing/', '/shiju/chunxin/', '/shiju/moyang/', '/shiju/wuji/',
                '/shiju/huacong/', '/shiju/zhuiyi/', '/shiju/chuanshu/', '/shiju/luqi/', '/shiju/wuliao/',
                '/shiju/yuxiao/', '/shiju/yeye1/', '/shiju/binglun/', '/shiju/luhua1/', '/shiju/yuhou/',
                '/shiju/chuchu/', '/shiju/qingshui/', '/shiju/jiajing/', '/shiju/youxiang/', '/shiju/chengwei/',
                '/shiju/wanghou/', '/shiju/guiren/', '/shiju/xuyu/', '/shiju/biancheng/', '/shiju/juanqu/',
                '/shiju/xiangqin/', '/shiju/jishui/', '/shiju/fengchen/', '/shiju/jinguyuan/', '/shiju/chengdu/',
                '/shiju/lvzhu/', '/shiju/yanxiao/', '/shiju/huangliang/', '/shiju/huangsha/', '/shiju/pingfeng/',
                '/shiju/jinshu/', '/shiju/chunqiu2/', '/shiju/zhaoyang/', '/shiju/luwei/', '/shiju/zhaoshu/',
                '/shiju/qushui/', '/shiju/renshi/', '/shiju/chenai/', '/shiju/baiou/', '/shiju/zhixin/', '/shiju/yeyu/',
                '/shiju/bitao/', '/shiju/buxiu/', '/shiju/tiantai/', '/shiju/tianzhu/', '/shiju/linyu/',
                '/shiju/yingke/', '/shiju/mihou/', '/shiju/songzi/', '/shiju/quanfei/', '/shiju/chengshi/',
                '/shiju/xinnian/', '/shiju/piaoyao/', '/shiju/qunian/', '/shiju/jinri/', '/shiju/boyi/', '/shiju/buqu/',
                '/shiju/huafei/', '/shiju/wuya/', '/shiju/ouran/', '/shiju/dengfeng/', '/shiju/tongzhi/',
                '/shiju/shengao/', '/shiju/duansong/', '/shiju/hunhun/', '/shiju/quexian/', '/shiju/gandan/',
                '/shiju/youhuan/', '/shiju/yeguo/', '/shiju/haiyu/', '/shiju/lulu/', '/shiju/xunhuan/',
                '/shiju/linlin/', '/shiju/linlin1/', '/shiju/yinghuo/', '/shiju/wanwan/', '/shiju/chengtou/',
                '/shiju/liangzhou/', '/shiju/huren/', '/shiju/jiujia/', '/shiju/liyu/', '/shiju/jiming/',
                '/shiju/pingan/', '/shiju/qiongyao/', '/shiju/juanjuan1/', '/shiju/suosuo/', '/shiju/qingxue/',
                '/shiju/sese/', '/shiju/congcong1/', '/shiju/shuanghua/', '/shiju/wanwu/', '/shiju/quyuan/',
                '/shiju/xiangyu/', '/shiju/fanchuan/', '/shiju/qiangu/', '/shiju/jiao/', '/shiju/jinglun/',
                '/shiju/wuneng/', '/shiju/shishu/', '/shiju/zhurong/', '/shiju/fuyao/', '/shiju/mengmei/',
                '/shiju/yingying1/', '/shiju/qiaoqiao/', '/shiju/xianglu/', '/shiju/xueshan/', '/shiju/qingliang/',
                '/shiju/zhongxiao/', '/shiju/qincai/', '/shiju/shiyu/', '/shiju/guiyu/', '/shiju/zaixiang/',
                '/shiju/congrong/', '/shiju/jiannan/', '/shiju/jianshui/', '/shiju/jueya/', '/shiju/shiliu/',
                '/shiju/hetun/', '/shiju/jiajia/', '/shiju/huanxiao/', '/shiju/fengwei/', '/shiju/duanduan/',
                '/shiju/dapeng/', '/shiju/guli/', '/shiju/baizhou/', '/shiju/xixi3/', '/shiju/xiangzhi/',
                '/shiju/shiye/', '/shiju/yazi/', '/shiju/youju/', '/shiju/yecai/', '/shiju/jiquan/', '/shiju/qingwa/',
                '/shiju/xia/', '/shiju/longlin/', '/shiju/hundun1/', '/shiju/huaping/', '/shiju/sanfu/',
                '/shiju/jizao/', '/shiju/meigui/', '/shiju/lianlizhi/', '/shiju/wudoumi/', '/shiju/pixiu/',
                '/shiju/mengchengjun/', '/shiju/zijinghua/', '/shiju/kuaiyu/', '/shiju/boli/', '/shiju/ziluan/',
                '/shiju/jiongjiong/', '/shiju/fenghou/', '/shiju/xiaoxiao1/', '/shiju/yihen/', '/shiju/songyu/',
                '/shiju/youyang/', '/shiju/huoshan/', '/shiju/feiniao/', '/shiju/hujia/', '/shiju/loulan/',
                '/shiju/weiwei/', '/shiju/juzi/', '/shiju/lei/', '/shiju/guanhe/', '/shiju/liguang/',
                '/shiju/qingchou/', '/shiju/jinlin/', '/shiju/tianji/', '/shiju/yuantian/', '/shiju/baiyan/',
                '/shiju/liqun/', '/shiju/chunhui/', '/shiju/bugui/', '/shiju/rumeng/', '/shiju/xiongdi/',
                '/shiju/luren/', '/shiju/shanhai/', '/shiju/fangcun/', '/shiju/qiannian/', '/shiju/guancai/',
                '/shiju/hanyang/', '/shiju/qingqing1/', '/shiju/shiguang/', '/shiju/qiuhao/', '/shiju/yishui/',
                '/shiju/wanjie/', '/shiju/liandan/', '/shiju/caiyao/', '/shiju/shuishou/', '/shiju/chuidiao/',
                '/shiju/piaoran/', '/shiju/changsha/', '/shiju/maijiu1/', '/shiju/gufan/', '/shiju/shishi1/',
                '/shiju/daolu/', '/shiju/qiankun/', '/shiju/louge/', '/shiju/shenling/', '/shiju/zhongxing/',
                '/shiju/huoyun/', '/shiju/fengchun/', '/shiju/xiangchou/', '/shiju/zhaoxi/', '/shiju/songchun/',
                '/shiju/yingchun/', '/shiju/zisun/', '/shiju/zhuozhuo/', '/shiju/jiuxiao/', '/shiju/ruhe/',
                '/shiju/ziran/', '/shiju/longgong/', '/shiju/jiasha/', '/shiju/xuanhua/', '/shiju/chuixu/',
                '/shiju/duixue/', '/shiju/qingzhen/', '/shiju/xiaozi/', '/shiju/taolue/', '/shiju/paoxiao/',
                '/shiju/shuguang/', '/shiju/chiru/', '/shiju/gufen/', '/shiju/shishouye/', '/shiju/longwang/',
                '/shiju/qinggao/', '/shiju/xuxin/', '/shiju/caiqi/', '/shiju/mengzhongren/', '/shiju/zhonglao/',
                '/shiju/pingping/', '/shiju/jinpen/', '/shiju/ranran1/', '/shiju/aiai1/', '/shiju/xiaopin1/',
                '/shiju/baye/', '/shiju/liuxiahui/', '/shiju/tianzhu1/', '/shiju/luobo/', '/shiju/jicai/',
                '/shiju/huaniao/', '/shiju/feifei1/', '/shiju/beihuan/', '/shiju/zongheng/', '/shiju/shaoyao/',
                '/shiju/baihe/', '/shiju/chahua1/', '/shiju/qiangwei/', '/shiju/xiaolian/', '/shiju/guanzhong/',
                '/shiju/xiaye/', '/shiju/qiuye1/', '/shiju/chunye/', '/shiju/dongye/', '/shiju/yuhui/', '/shiju/lisi/',
                '/shiju/qiuyi/', '/shiju/qingqiu1/', '/shiju/yiyi1/', '/shiju/zhuye/', '/shiju/changge/',
                '/shiju/duange/', '/shiju/danxi/', '/shiju/jiangtou/', '/shiju/shuangyu/', '/shiju/shaozhuang/',
                '/shiju/yumao/', '/shiju/chanchu/', '/shiju/jiangliu/', '/shiju/tiema/', '/shiju/jingwei/',
                '/shiju/huanghu/', '/shiju/xinyi/', '/shiju/xinyi1/', '/shiju/xinyi2/', '/shiju/xianshi/',
                '/shiju/zhifu/', '/shiju/beiai/', '/shiju/longshou/', '/shiju/kunan/', '/shiju/jiyan/',
                '/shiju/duanjue/', '/shiju/qihu/', '/shiju/danqiusheng/', '/shiju/yuntai/', '/shiju/shuilu/',
                '/shiju/taigong/', '/shiju/wuyi/', '/shiju/kangle/', '/shiju/nantian/', '/shiju/hongfei/',
                '/shiju/yinqi/', '/shiju/shibi/', '/shiju/yanyu1/', '/shiju/guangming/', '/shiju/huqiu/',
                '/shiju/yuwei/', '/shiju/rujia/', '/shiju/ruzhe/', '/shiju/linjia/', '/shiju/chengming/',
                '/shiju/wuzhi/', '/shiju/zhiji/', '/shiju/shengse/', '/shiju/qiwei/', '/shiju/panghuang/',
                '/shiju/jiasheng/', '/shiju/nanwei/', '/shiju/luanshi/', '/shiju/huohuan/', '/shiju/wuduan/',
                '/shiju/jikang/', '/shiju/lingyu/', '/shiju/yazi1/', '/shiju/pulao/', '/shiju/suanni/', '/shiju/bian/',
                '/shiju/chunhua2/', '/shiju/sangtian/', '/shiju/haishui/', '/shiju/fanfu/', '/shiju/bingren/',
                '/shiju/buzhi/', '/shiju/buyi1/', '/shiju/chongji/', '/shiju/tiandao/', '/shiju/pinfu/',
                '/shiju/shuangye/', '/shiju/wangnian/', '/shiju/tianyi/', '/shiju/wujian/', '/shiju/nifeng/',
                '/shiju/huangdi/', '/shiju/qingguang/', '/shiju/chunmu/', '/shiju/zaixiong/', '/shiju/zuzong/',
                '/shiju/suye/', '/shiju/chongchong/', '/shiju/miaomiao/', '/shiju/weiwei1/', '/shiju/benteng/',
                '/shiju/tianye/', '/shiju/xiuxian/', '/shiju/xiangshan/', '/shiju/chixin/', '/shiju/xinhun/',
                '/shiju/huanhu/', '/shiju/zhizi/', '/shiju/sijia/', '/shiju/fengzi/', '/shiju/jiuchongtian/',
                '/shiju/danqie/', '/shiju/chengjiu/', '/shiju/shengzhang/', '/shiju/haodang/', '/shiju/heqi/',
                '/shiju/wangzhe/', '/shiju/huangtian/', '/shiju/wanggong/', '/shiju/jisi/', '/shiju/tianjiang1/',
                '/shiju/zilian/', '/shiju/huangcao/', '/shiju/zhuojiu/', '/shiju/botao/', '/shiju/fanfan/',
                '/shiju/ranran2/', '/shiju/qiangqiang/', '/shiju/huozhe/', '/shiju/xiake/', '/shiju/diedie/',
                '/shiju/yeren/', '/shiju/gucheng/', '/shiju/zhonghua/', '/shiju/zhongshu/', '/shiju/jiaotu/',
                '/shiju/hainiao/', '/shiju/jiji1/', '/shiju/yangyang/', '/shiju/saoxue/', '/shiju/yinger/',
                '/shiju/linggen/', '/shiju/dandan1/', '/shiju/yaoqi/', '/shiju/shise/', '/shiju/bobo/', '/shiju/hukou/',
                '/shiju/renai/', '/shiju/tongyan/', '/shiju/chiqing/', '/shiju/qingluan/', '/shiju/jingyanggong/',
                '/shiju/changxingong/', '/shiju/linjiao/', '/shiju/fengmao/', '/shiju/siwen/', '/shiju/daminggong/',
                '/shiju/apanggong/', '/shiju/cixiang/', '/shiju/jiusui/', '/shiju/moshang/', '/shiju/ermei/',
                '/shiju/changjiu/', '/shiju/jiangshang/', '/shiju/yanmai/', '/shiju/zigui/', '/shiju/nvqiang/',
                '/shiju/chuci/', '/shiju/bohe/', '/shiju/fuling/', '/shiju/tianma/', '/shiju/gouqi/', '/shiju/renshen/',
                '/shiju/gancao/', '/shiju/huanglian/', '/shiju/fuzi1/', '/shiju/xixin/', '/shiju/qianshi/',
                '/shiju/suanzao/', '/shiju/shengjiang/', '/shiju/hujiao/', '/shiju/jiaxiang/', '/shiju/buluo/',
                '/shiju/shanzha/', '/shiju/heye/', '/shiju/hanmei/', '/shiju/qiushi/', '/shiju/oulu/',
                '/shiju/xianweng/', '/shiju/qipan/', '/shiju/xiushu/', '/shiju/dumuqiao/', '/shiju/yinyin1/',
                '/shiju/renjia/', '/shiju/laonong/', '/shiju/wulin/', '/shiju/jihui/', '/shiju/linli/',
                '/shiju/shancheng/', '/shiju/gankai/', '/shiju/zizhi/', '/shiju/chanke/', '/shiju/huashi/',
                '/shiju/zicai/', '/shiju/haicao/', '/shiju/zaizhu/', '/shiju/youzi1/', '/shiju/xiongzhuang/',
                '/shiju/guyuanqing/', '/shiju/shuiliandong/', '/shiju/mugua/', '/shiju/xishuai/', '/shiju/qinling/',
                '/shiju/ganlusi/', '/shiju/lingyinsi/', '/shiju/xichansi/', '/shiju/shaolinsi/', '/shiju/famen/',
                '/shiju/baimasi/', '/shiju/wolong/', '/shiju/chengxiang/', '/shiju/shuixian/', '/shiju/guqi/',
                '/shiju/baihe1/', '/shiju/jingke/', '/shiju/jiangyue/', '/shiju/baicai/', '/shiju/kugua/',
                '/shiju/tiangua/', '/shiju/jinguancheng/', '/shiju/fuzi2/', '/shiju/miaotang/', '/shiju/sigua/',
                '/shiju/jushu/', '/shiju/jiulou/', '/shiju/fengsu/', '/shiju/yanhuo/', '/shiju/ganji/',
                '/shiju/xinzhong/', '/shiju/yinghua/', '/shiju/yelu/', '/shiju/qingjiu/', '/shiju/zhuren/',
                '/shiju/bimo/', '/shiju/renshi1/', '/shiju/shijun/', '/shiju/chuqing/', '/shiju/yupan/',
                '/shiju/mingnian/', '/shiju/hechu/', '/shiju/qingyun1/', '/shiju/wusheng/', '/shiju/wuwei/',
                '/shiju/mailang/', '/shiju/yunhai/', '/shiju/qingjing/', '/shiju/wuwei1/', '/shiju/yuxiao1/',
                '/shiju/feixu/', '/shiju/fengcai/', '/shiju/shenyou/', '/shiju/xiuzhu/', '/shiju/lingnan/',
                '/shiju/tianxiao/', '/shiju/taoxing/', '/shiju/xianxin/', '/shiju/qinglei/', '/shiju/wuxiang/',
                '/shiju/fengshui/', '/shiju/caolu/', '/shiju/zhanyi/', '/shiju/youchou/', '/shiju/wushan1/',
                '/shiju/guiqu/', '/shiju/rongyan/', '/shiju/jiangcun/', '/shiju/meixue/', '/shiju/chongfeng/',
                '/shiju/jinmen/', '/shiju/xunchang/', '/shiju/luoshan/', '/shiju/qingxu/', '/shiju/lili1/',
                '/shiju/jiayuan/', '/shiju/lengdan/', '/shiju/tizi/', '/shiju/shisanling/', '/shiju/yehuo/',
                '/shiju/qiukong/', '/shiju/luomu/', '/shiju/lianzi/', '/shiju/liren/', '/shiju/wuxian/',
                '/shiju/guiqi/', '/shiju/shuoyun/', '/shiju/muyu/', '/shiju/zixi/', '/shiju/loushui/',
                '/shiju/yusheng/', '/shiju/chengfeng/', '/shiju/zhuying/', '/shiju/cema/', '/shiju/jinsuo/',
                '/shiju/xiliu/', '/shiju/biyu/', '/shiju/zhizun/', '/shiju/meilin/', '/shiju/xiangwang/',
                '/shiju/wumeng/', '/shiju/xingming1/', '/shiju/yingtou/', '/shiju/tongxiao/', '/shiju/candong/',
                '/shiju/gongye/', '/shiju/qingting/', '/shiju/lingjiao/', '/shiju/maodun/', '/shiju/wangwang/',
                '/shiju/xianghuo/', '/shiju/jingji/', '/shiju/chitang/', '/shiju/shengri/', '/shiju/jinzi/',
                '/shiju/ruyi/', '/shiju/qionghua/', '/shiju/piaobo/', '/shiju/laisheng/', '/shiju/mohu/',
                '/shiju/shuimo/', '/shiju/buyecheng/', '/shiju/yuwang/', '/shiju/sangye/', '/shiju/lusi/',
                '/shiju/gusu/', '/shiju/jiaohua/', '/shiju/huajiao/', '/shiju/manyou/', '/shiju/caizi/',
                '/shiju/zhenzhong/', '/shiju/guilu/', '/shiju/panzhe/', '/shiju/zhuangxin/', '/shiju/shaou/',
                '/shiju/diaogan/', '/shiju/yuanyou/', '/shiju/guzhou/', '/shiju/qingxin/', '/shiju/gumu1/',
                '/shiju/baiyang/', '/shiju/kuangye/', '/shiju/yangguang/', '/shiju/sanchun/', '/shiju/mengchun/',
                '/shiju/zhongchun/', '/shiju/jichun/', '/shiju/mengxia/', '/shiju/zhongxia/', '/shiju/jixia/',
                '/shiju/mengqiu/', '/shiju/zhongqiu/', '/shiju/jiqiu/', '/shiju/mengdong/', '/shiju/zhongdong/',
                '/shiju/jidong/', '/shiju/zhiqian/', '/shiju/muqiu/', '/shiju/chengchi/', '/shiju/eyun/',
                '/shiju/yeniao/', '/shiju/qiqiao/', '/shiju/momo2/', '/shiju/buyi2/', '/shiju/zuoyou/',
                '/shiju/chushibiao/', '/shiju/wuse/', '/shiju/lvlin/', '/shiju/qihou/', '/shiju/shanhe/',
                '/shiju/wangshi1/', '/shiju/hongxing/', '/shiju/chuji/', '/shiju/niaoming/', '/shiju/sigui/',
                '/shiju/guanxi/', '/shiju/pingshan/', '/shiju/huanian/', '/shiju/mosuo/', '/shiju/langji/',
                '/shiju/ruhua/', '/shiju/qingyan/', '/shiju/xiaomo/', '/shiju/yuanlin/', '/shiju/fangyou/',
                '/shiju/laosou/', '/shiju/qiongku/', '/shiju/baiyi/', '/shiju/chengtiansi/', '/shiju/niliu/',
                '/shiju/yuanquan/', '/shiju/banyue/', '/shiju/cangliang/', '/shiju/juanlian/', '/shiju/yuse/',
                '/shiju/shenshi/', '/shiju/tianchou/', '/shiju/jiaojiao/', '/shiju/zhenzhu/', '/shiju/yushi/',
                '/shiju/yingluo/', '/shiju/zhizihua/', '/shiju/fenghan/', '/shiju/saorao/', '/shiju/yaodai/',
                '/shiju/tiaodeng/', '/shiju/cuoluo/', '/shiju/jijing/', '/shiju/quxi/', '/shiju/xuxu/',
                '/shiju/qianqian/', '/shiju/yidai/', '/shiju/guiren1/', '/shiju/xingxing2/', '/shiju/shici/',
                '/shiju/diaoqiu/', '/shiju/xiangnv/', '/shiju/guixin/', '/shiju/jiangzhong/', '/shiju/daomiao/',
                '/shiju/gumi/', '/shiju/qiezi/', '/shiju/mili/', '/shiju/shizi1/', '/shiju/xinyu1/', '/shiju/nisha/',
                '/shiju/xiaofeng/', '/shiju/meijian1/', '/shiju/caise/', '/shiju/meiling/', '/shiju/feiniu/',
                '/shiju/zhenxing/', '/shiju/shenyuan/', '/shiju/piaohu/', '/shiju/fajiu/', '/shiju/huanle/',
                '/shiju/tengwangge/', '/shiju/luoxia/', '/shiju/yushu/', '/shiju/zaihui/', '/shiju/tianqiao/',
                '/shiju/wangsun/', '/shiju/cenci/', '/shiju/zhuzhi/', '/shiju/guowai/', '/shiju/tushu/',
                '/shiju/huangcun/', '/shiju/qima/', '/shiju/quche/', '/shiju/cangzhou/', '/shiju/jiubu/',
                '/shiju/ying1/', '/shiju/wanqing/', '/shiju/riri/', '/shiju/fanfan1/', '/shiju/zhongtian/',
                '/shiju/lingshan/', '/shiju/yejing/', '/shiju/lvcao/', '/shiju/huma/', '/shiju/wenzi/',
                '/shiju/wenzi1/', '/shiju/lingling/', '/shiju/hanshui/', '/shiju/shangyanggong/', '/shiju/yunxiao/',
                '/shiju/haitianyao/', '/shiju/yaowang/', '/shiju/luoying/', '/shiju/jiaguo/', '/shiju/yingzhua/',
                '/shiju/denglong/', '/shiju/fuqu/', '/shiju/chushui/', '/shiju/yongbie/', '/shiju/chizhongwu/',
                '/shiju/yueyue/', '/shiju/tianfu/', '/shiju/xiedaowen/', '/shiju/qianhua/', '/shiju/yinghua1/',
                '/shiju/wu/', '/shiju/yueniao/', '/shiju/langdang/', '/shiju/guoshang/', '/shiju/muye/',
                '/shiju/jingtu/', '/shiju/cifu/', '/shiju/chensha/', '/shiju/dangzi/', '/shiju/yugu/', '/shiju/wuli/',
                '/shiju/fangfu/', '/shiju/tianhan/', '/shiju/pianpian1/', '/shiju/qigu/', '/shiju/yindeng/',
                '/shiju/hangzhou/', '/shiju/cishi1/', '/shiju/qianqian1/', '/shiju/dengxian/', '/shiju/moe/',
                '/shiju/qiushan/', '/shiju/mengxing/', '/shiju/caifeng/', '/shiju/guzheng/', '/shiju/qixin/',
                '/shiju/yian/', '/shiju/kuxin1/', '/shiju/ciqu/', '/shiju/honghu/', '/shiju/gaofei/', '/shiju/yuandao/',
                '/shiju/changlu/', '/shiju/xieshou/', '/shiju/yiji/', '/shiju/baicao/', '/shiju/shengshuai/',
                '/shiju/yanruyu/', '/shiju/shuangfeiyan/', '/shiju/qianzai/', '/shiju/buyao/', '/shiju/manao/',
                '/shiju/guanshui/', '/shiju/gaojie1/', '/shiju/shuijinggong/', '/shiju/yunmu/', '/shiju/jiaojie/',
                '/shiju/haoyue/', '/shiju/shiquan/', '/shiju/xiaoguan/', '/shiju/hushui/', '/shiju/xianggong/',
                '/shiju/shanyin/', '/shiju/langan/', '/shiju/lvguan/', '/shiju/tianji1/', '/shiju/gedou/',
                '/shiju/hedao/', '/shiju/qingshe/', '/shiju/xuri/', '/shiju/jinbei/', '/shiju/yaotai/',
                '/shiju/qiongjiang/', '/shiju/nuli/', '/shiju/tanxiao/', '/shiju/kugao/', '/shiju/wuqiong/',
                '/shiju/liren1/', '/shiju/xibing/', '/shiju/yejian/', '/shiju/ganjiang/', '/shiju/moxie/',
                '/shiju/jianqie/', '/shiju/benyin/', '/shiju/guancang/', '/shiju/jishi/', '/shiju/yuzhe/',
                '/shiju/xianzhe/', '/shiju/zhizhe/', '/shiju/touhu/', '/shiju/sanqin/', '/shiju/shuzha/',
                '/shiju/wanjuanshu/', '/shiju/houshi/', '/shiju/tongpao/', '/shiju/yuanfang/', '/shiju/tianbian/',
                '/shiju/hehuan/', '/shiju/jinghu/', '/shiju/ganwu/', '/shiju/shizhi/', '/shiju/hexu/', '/shiju/qinshu/',
                '/shiju/renyi/', '/shiju/menqian/', '/shiju/dasha/', '/shiju/pingping1/', '/shiju/shashi/',
                '/shiju/purong/', '/shiju/fufu/', '/shiju/jiaoye/', '/shiju/jiaobai/', '/shiju/quanxi/',
                '/shiju/shuangfeng/', '/shiju/xiaqi1/', '/shiju/shenwu/', '/shiju/fujun/', '/shiju/rongshuai/',
                '/shiju/zaohua1/', '/shiju/gaoshi/', '/shiju/duanni/', '/shiju/xiushi/', '/shiju/gengli/',
                '/shiju/wuhuo/', '/shiju/beimangshan/', '/shiju/yilun/', '/shiju/xiaci/', '/shiju/liyue/',
                '/shiju/enqing/', '/shiju/liuqin/', '/shiju/lieshi/', '/shiju/anju/', '/shiju/zhongzhen/',
                '/shiju/munian/', '/shiju/jiabing/', '/shiju/shizhi1/', '/shiju/lihe/', '/shiju/qiuchang/',
                '/shiju/mache/', '/shiju/xima/', '/shiju/dongxi/', '/shiju/ganku/', '/shiju/yixi/', '/shiju/linzhong/',
                '/shiju/qianwan/', '/shiju/wangqing/', '/shiju/jiku/', '/shiju/wuya1/', '/shiju/zhuge/',
                '/shiju/gongli/', '/shiju/bianfa/', '/shiju/yingcai/', '/shiju/fushi1/', '/shiju/leshi/',
                '/shiju/tianwei/', '/shiju/kaiyuan/', '/shiju/wenming/', '/shiju/ganren/', '/shiju/wenrouxiang/',
                '/shiju/louyi/', '/shiju/zuoshi/', '/shiju/changting/', '/shiju/zhuhua/', '/shiju/wuchangyu/',
                '/shiju/chumu/', '/shiju/guanshanyue/', '/shiju/chouhen/', '/shiju/yiran/', '/shiju/wangxie/',
                '/shiju/canzhuang/', '/shiju/chunchou/', '/shiju/jieshi/', '/shiju/yeshu/', '/shiju/yinshi/',
                '/shiju/huofu/', '/shiju/mengzi/', '/shiju/qingchi/', '/shiju/yaoshi/', '/shiju/chuxin/',
                '/shiju/anwei/', '/shiju/baling/', '/shiju/baimi/', '/shiju/fengmi/', '/shiju/huarui/', '/shiju/sheji/',
                '/shiju/gongxian/', '/shiju/laoku/', '/shiju/houdai/', '/shiju/jianghang/', '/shiju/shizhe/',
                '/shiju/geyao/', '/shiju/xingxiang/', '/shiju/baiyin/', '/shiju/tianshu/', '/shiju/tanlang/',
                '/shiju/yuheng/', '/shiju/biange/', '/shiju/shangyuan/', '/shiju/shuicao/', '/shiju/youyu1/',
                '/shiju/xiancai/', '/shiju/kuangshi/', '/shiju/yifu/', '/shiju/chentu/', '/shiju/guanxi1/',
                '/shiju/loutai/', '/shiju/shichuang/', '/shiju/tuhua/', '/shiju/lianmu/', '/shiju/chuyou/',
                '/shiju/edu/', '/shiju/guanghangong/', '/shiju/yutu/', '/shiju/ershisiqiao/', '/shiju/zhulian/',
                '/shiju/diaochan/', '/shiju/sisheng/', '/shiju/aoxiang/', '/shiju/lianxi/', '/shiju/manyi/',
                '/shiju/suihan/', '/shiju/anxiang/', '/shiju/lihua1/', '/shiju/cibei/', '/shiju/jiapin/',
                '/shiju/caiqi1/', '/shiju/baisou/', '/shiju/huangtong/', '/shiju/haoran/', '/shiju/anfen/',
                '/shiju/meipo/', '/shiju/lantian/', '/shiju/canggou/', '/shiju/canglong/', '/shiju/laoseng/',
                '/shiju/shuzhi/', '/shiju/gaodi/', '/shiju/xingyue/', '/shiju/bingxue/', '/shiju/dongchuang/',
                '/shiju/yucong/', '/shiju/guyue/', '/shiju/wanxiang/', '/shiju/weimian/', '/shiju/yehehua/',
                '/shiju/wuyuan/', '/shiju/jindan/', '/shiju/wanhuhou/', '/shiju/zhilan/', '/shiju/nvwa/',
                '/shiju/yuanque/', '/shiju/gongque/', '/shiju/jinxi/', '/shiju/xiuxing/', '/shiju/xiongyong/',
                '/shiju/huaxiang/', '/shiju/muxu/', '/shiju/xidi/', '/shiju/mutian/', '/shiju/mutianxidi/',
                '/shiju/chuanjia/', '/shiju/sangma/', '/shiju/anzhai/', '/shiju/fengxin/', '/shiju/zongji/',
                '/shiju/wuji1/', '/shiju/riye/', '/shiju/wenwu1/', '/shiju/baiyu2/', '/shiju/jiaqu/', '/shiju/shengyu/',
                '/shiju/zhongsang/', '/shiju/haibian/', '/shiju/zhengfan/', '/shiju/huangliang1/', '/shiju/zhongding/',
                '/shiju/yurou/', '/shiju/saoren/', '/shiju/zhengchun/', '/shiju/fengchou/', '/shiju/jinchai/',
                '/shiju/pirou/', '/shiju/bagua/', '/shiju/guaqi/', '/shiju/linjia1/', '/shiju/qianqian2/',
                '/shiju/yangsheng/', '/shiju/pingzhang/', '/shiju/huoran/', '/shiju/dongshan/', '/shiju/daoqi/',
                '/shiju/maoling/', '/shiju/shuanghua1/', '/shiju/tianmen/', '/shiju/zhujian/', '/shiju/jiaqi/',
                '/shiju/yancao/', '/shiju/sangyu/', '/shiju/luntai/', '/shiju/zhengma/', '/shiju/shashu/',
                '/shiju/jiaxue/', '/shiju/ganchang/', '/shiju/jiafa/', '/shiju/xietiao/', '/shiju/dushe/',
                '/shiju/mingchen/', '/shiju/saoshou/', '/shiju/weiba/', '/shiju/lulu1/', '/shiju/bikong/',
                '/shiju/gongde/', '/shiju/liufang/', '/shiju/lige/', '/shiju/wali/', '/shiju/zizu/', '/shiju/shangu/',
                '/shiju/chuangtou/', '/shiju/zhonglie/', '/shiju/anle/', '/shiju/qiaozhuo/', '/shiju/congming/',
                '/shiju/shengling/', '/shiju/baixing/', '/shiju/weifeng/', '/shiju/weifeng1/', '/shiju/chizi/',
                '/shiju/cunluo/', '/shiju/niangzi/', '/shiju/jingming/', '/shiju/shubei/', '/shiju/puti/',
                '/shiju/jiangbian/', '/shiju/fannao/', '/shiju/gongjing/', '/shiju/huihuo/', '/shiju/taiyuan/',
                '/shiju/xindong/', '/shiju/panyang/', '/shiju/panyanghu/', '/shiju/liuying/', '/shiju/niaoyu/',
                '/shiju/xiari/', '/shiju/qiuju/', '/shiju/baojian/', '/shiju/deyi/', '/shiju/zhongtian1/',
                '/shiju/penghao/', '/shiju/disheng/', '/shiju/ruixue/', '/shiju/qiusi/', '/shiju/yanan/',
                '/shiju/zhongyi/', '/shiju/hen/', '/shiju/heliu/', '/shiju/qilianshan/', '/shiju/wudinghe/',
                '/shiju/ruhua1/', '/shiju/riguang/', '/shiju/lang/', '/shiju/ruyan/', '/shiju/damo/', '/shiju/yanhou/',
                '/shiju/yandangshan/', '/shiju/hengshan/', '/shiju/hengshan1/', '/shiju/songshan/',
                '/shiju/wudangshan1/', '/shiju/qingchengshan/', '/shiju/wutaishan1/', '/shiju/emeishan1/',
                '/shiju/jiuhuashan/', '/shiju/chuqiu/', '/shiju/shenqiu/', '/shiju/xinyuan/', '/shiju/yeyu1/',
                '/shiju/chidai/', '/shiju/bilin/', '/shiju/jishu/', '/shiju/sasa/', '/shiju/qiren/', '/shiju/dengta/',
                '/shiju/kaixuan/', '/shiju/shengnian/', '/shiju/banlan/', '/shiju/bianshi/', '/shiju/ganyu/',
                '/shiju/congjun/', '/shiju/yiliu/', '/shiju/shouhu/', '/shiju/xiangyun/', '/shiju/maofa/',
                '/shiju/xiqi/', '/shiju/maoniu/', '/shiju/jiaoyang/', '/shiju/shanxi/', '/shiju/jiangshuai/',
                '/shiju/xiangju/', '/shiju/sixin/', '/shiju/liangliang/', '/shiju/shili1/', '/shiju/qizhi/',
                '/shiju/renming/', '/shiju/kongzi/', '/shiju/baobian/', '/shiju/caiyi/', '/shiju/baiban/',
                '/shiju/tianshe/', '/shiju/buxi/', '/shiju/yuyi/', '/shiju/xiumu/', '/shiju/miren/', '/shiju/kuaihuo/',
                '/shiju/housi/', '/shiju/huanghu1/', '/shiju/dongwu/', '/shiju/gudi/', '/shiju/heibai/',
                '/shiju/liaoli/', '/shiju/qiju/', '/shiju/fangyuan/', '/shiju/bazhentu/', '/shiju/zhuma/',
                '/shiju/moyan/', '/shiju/guike/', '/shiju/youzai/', '/shiju/zaihua/', '/shiju/tanqin/',
                '/shiju/rongshen/', '/shiju/haosheng/', '/shiju/xiangguan/', '/shiju/gongshi/', '/shiju/yiren/',
                '/shiju/junjie/', '/shiju/qingjie/', '/shiju/zhuangyuan/', '/shiju/bangyan/', '/shiju/tanhua/',
                '/shiju/huasheng/', '/shiju/shijing/', '/shiju/tiantaishan/', '/shiju/naihe/', '/shiju/wangyoucao/',
                '/shiju/mantian/', '/shiju/chelun/', '/shiju/caose/', '/shiju/niangjiu/', '/shiju/yusheng1/',
                '/shiju/yuefeng/', '/shiju/jiejian/', '/shiju/shiyan/', '/shiju/lvren/', '/shiju/aicai/',
                '/shiju/guigongzi/', '/shiju/langyan/', '/shiju/jiejiao/', '/shiju/shizhong/', '/shiju/xunmi/',
                '/shiju/baitouyin/', '/shiju/jiuse/', '/shiju/wuxing/', '/shiju/zhubao/', '/shiju/baozang/',
                '/shiju/tongling/', '/shiju/zhuangyuanhong/', '/shiju/yanjing/', '/shiju/bamin/', '/shiju/jiutu/',
                '/shiju/luding/', '/shiju/qixiao/', '/shiju/fangbang/', '/shiju/xiangyang/', '/shiju/guanlu/',
                '/shiju/qiuguan/', '/shiju/danbi/', '/shiju/jihan/', '/shiju/yutian/', '/shiju/zuijiu/',
                '/shiju/hulang/', '/shiju/langya1/', '/shiju/fentu/', '/shiju/daode/', '/shiju/bianchi/',
                '/shiju/jiji2/', '/shiju/jiaoqing/', '/shiju/meishaonian/', '/shiju/shaonv/', '/shiju/luyv/',
                '/shiju/chungui1/', '/shiju/zhenxiu/', '/shiju/jingxi/', '/shiju/xinxi/', '/shiju/gouhuo/',
                '/shiju/zhaozhao/', '/shiju/diewu/', '/shiju/yaocao/', '/shiju/kuangfeng/', '/shiju/yingfeng/',
                '/shiju/qingya/', '/shiju/gaoya/', '/shiju/duanzhuang/', '/shiju/qingxin1/', '/shiju/xinxian/',
                '/shiju/jinhua/', '/shiju/gusui/', '/shiju/shuihuo/', '/shiju/fantai/', '/shiju/fanren/',
                '/shiju/ruiqi/', '/shiju/jixiang/', '/shiju/liushu/', '/shiju/baitouweng/', '/shiju/canhua/',
                '/shiju/liuhuang/', '/shiju/wuyin/', '/shiju/liulv/', '/shiju/qingniao/', '/shiju/laodong/',
                '/shiju/wenshu/', '/shiju/fangzhang/', '/shiju/xiaoxi1/', '/shiju/huajie/', '/shiju/lizhi2/',
                '/shiju/jinlian/', '/shiju/chanshi/', '/shiju/guanyin/', '/shiju/liaoran/', '/shiju/lushui/',
                '/shiju/luzhu/', '/shiju/shuiniao/', '/shiju/zhongxing1/', '/shiju/qunxing/', '/shiju/qingnian/',
                '/shiju/baizhu/', '/shiju/miaomiao1/', '/shiju/quanjun/', '/shiju/ganquan/', '/shiju/wanglai/',
                '/shiju/baita/', '/shiju/guitu/', '/shiju/hongri/', '/shiju/suiyuan/', '/shiju/qujing/',
                '/shiju/zuoke/', '/shiju/tingche/', '/shiju/fofa/', '/shiju/quzhi/', '/shiju/guangmang/',
                '/shiju/jianer/', '/shiju/shenshou/', '/shiju/jinyi/', '/shiju/tahua/', '/shiju/haohua/',
                '/shiju/shechi/', '/shiju/luoque/', '/shiju/chibi/', '/shiju/shuangqin/', '/shiju/shouma/',
                '/shiju/youzhou/', '/shiju/qingshi/', '/shiju/fenmo/', '/shiju/xishi/', '/shiju/wangzhaoju/',
                '/shiju/songxing/', '/shiju/piaobo1/', '/shiju/binghu/', '/shiju/sanhuai/', '/shiju/sima/',
                '/shiju/gaomen/', '/shiju/zibei/', '/shiju/qunfang/', '/shiju/jingcheng/', '/shiju/diwang/',
                '/shiju/qiaomai1/', '/shiju/chenzi/', '/shiju/jianghai/', '/shiju/jinhua1/', '/shiju/fuxin/',
                '/shiju/youqingren/', '/shiju/muzi/', '/shiju/zhiximei/', '/shiju/guonian/', '/shiju/lamei/',
                '/shiju/xinhan/', '/shiju/shiwang/', '/shiju/tongxin/', '/shiju/huaxu/', '/shiju/ya/',
                '/shiju/hongdou/', '/shiju/heidou/', '/shiju/huangdou/', '/shiju/douzi/', '/shiju/zitan/',
                '/shiju/wandou/', '/shiju/candou/', '/shiju/qingdou/', '/shiju/doujia/', '/shiju/qingxiang/',
                '/shiju/qianniuxing/', '/shiju/gaoyuan/', '/shiju/jingtao/', '/shiju/xiane/', '/shiju/yeguang/',
                '/shiju/wushirenfei/', '/shiju/guijian/', '/shiju/xingyun/', '/shiju/zhongsheng1/', '/shiju/zhouxuan/',
                '/shiju/emao/', '/shiju/douhua/', '/shiju/jingzhou/', '/shiju/jiangling/', '/shiju/sinan/',
                '/shiju/chunlei/', '/shiju/jiaoyou/', '/shiju/yangmei1/', '/shiju/jietuo/', '/shiju/tubo/',
                '/shiju/jiaren1/', '/shiju/zumou/', '/shiju/mousheng/', '/shiju/linlin2/', '/shiju/chengguo/',
                '/shiju/chengqiang/', '/shiju/gucheng1/', '/shiju/lv/', '/shiju/nufu/', '/shiju/ruanruo/',
                '/shiju/jianqiang/', '/shiju/hualiu/', '/shiju/xiongcai/', '/shiju/chuzhong/', '/shiju/li/',
                '/shiju/xingdou/', '/shiju/buyu/', '/shiju/mengjian/', '/shiju/zizi/', '/shiju/xiedai/',
                '/shiju/xunsi/', '/shiju/jiangxue/', '/shiju/xueye/', '/shiju/jian2/', '/shiju/nu/', '/shiju/qinghai/',
                '/shiju/liulian/', '/shiju/shanren/', '/shiju/qianbei/', '/shiju/yinqing/', '/shiju/dezhi/',
                '/shiju/zhiyuan/', '/shiju/chuidi/', '/shiju/fengyun1/', '/shiju/guwangjinlai/', '/shiju/kuihua/',
                '/shiju/lixiang/', '/shiju/liuzhi/', '/shiju/chuiyang/', '/shiju/weiyang/', '/shiju/xishui/',
                '/shiju/xingqu/', '/shiju/qingsi/', '/shiju/niu/', '/shiju/huangniuxia/', '/shiju/yu2/',
                '/shiju/chenxiang/', '/shiju/tianse/', '/shiju/hunyin/', '/shiju/qinshi/', '/shiju/haiyan/',
                '/shiju/zaomei/', '/shiju/nianzhang/', '/shiju/mingzi/', '/shiju/feibing/', '/shiju/pibing/',
                '/shiju/kuhai/', '/shiju/enai/', '/shiju/wenjin/', '/shiju/mitu/', '/shiju/bangge/', '/shiju/qingxian/',
                '/shiju/dongfang1/', '/shiju/qiuyi1/', '/shiju/jiancha/', '/shiju/xidi1/', '/shiju/jianku/',
                '/shiju/kunku/', '/shiju/duli/', '/shiju/danfeng/', '/shiju/wangguo/', '/shiju/hudie/', '/shiju/feie/',
                '/shiju/weiyi/', '/shiju/chuniao/', '/shiju/zhiyuan1/', '/shiju/tiantan/', '/shiju/yanjing1/',
                '/shiju/jiaolou/', '/shiju/juyongguan/', '/shiju/yanmenguan/', '/shiju/jingzhou1/', '/shiju/tianjin/',
                '/shiju/zhaozhouqiao/', '/shiju/yizhou/', '/shiju/buguniao/', '/shiju/huaigu/', '/shiju/fuhua/',
                '/shiju/yuchuan/', '/shiju/zaishu/', '/shiju/jiaoyang1/', '/shiju/yuxue/', '/shiju/jiuding/',
                '/shiju/yuren/', '/shiju/yumei/', '/shiju/xingwu/', '/shiju/xiangshui/', '/shiju/pinqiong/',
                '/shiju/jiuxiang/', '/shiju/beishang/', '/shiju/xinglunan/', '/shiju/bieshu/', '/shiju/caotang/',
                '/shiju/caolu1/', '/shiju/ziye/', '/shiju/wuye1/', '/shiju/banye/', '/shiju/fendie/', '/shiju/jiuqi/',
                '/shiju/qiangguan/', '/shiju/hanlin/', '/shiju/fenzhuang/', '/shiju/chansheng/', '/shiju/xiangsi1/',
                '/shiju/sangshu/', '/shiju/jiading/', '/shiju/fenli/', '/shiju/qiongshu/', '/shiju/taixian/',
                '/shiju/niaoque/', '/shiju/cidihua/', '/shiju/songsheng/', '/shiju/chanshi1/', '/shiju/wanyan/',
                '/shiju/gupan/', '/shiju/feixiang/', '/shiju/yinyi/', '/shiju/shengfu/', '/shiju/deshi/',
                '/shiju/xinsuan/', '/shiju/haoli/', '/shiju/weibo/', '/shiju/shuoyan/', '/shiju/beige/',
                '/shiju/tianhuang/', '/shiju/potianhuang/', '/shiju/jinyu/', '/shiju/nanjing/', '/shiju/liaohua/',
                '/shiju/caimi/', '/shiju/huangfeng/', '/shiju/xihua/', '/shiju/huangque/', '/shiju/yanyulou/',
                '/shiju/dongqing/', '/shiju/longzhu/', '/shiju/yemingzhu/', '/shiju/huazhao/', '/shiju/liefu/',
                '/shiju/hanchan/', '/shiju/feiyan/', '/shiju/xinxing/', '/shiju/xingqing/', '/shiju/baizhi1/',
                '/shiju/xiangqi/', '/shiju/dengguang/', '/shiju/qimiao/', '/shiju/qite/', '/shiju/meimao/',
                '/shiju/jinghua1/', '/shiju/jiaoe/', '/shiju/huabao/', '/shiju/suwu/', '/shiju/kongmeng/',
                '/shiju/biduan/', '/shiju/jiangxin/', '/shiju/yaoshun/', '/shiju/yishu/', '/shiju/zaopo/',
                '/shiju/luanma/', '/shiju/mengya/', '/shiju/yecheng/', '/shiju/weicheng/', '/shiju/dianzhui/',
                '/shiju/zizhi1/', '/shiju/tianzi1/', '/shiju/tianfu1/', '/shiju/kuanwei/', '/shiju/xinwei/',
                '/shiju/guizhou/', '/shiju/zhuji/', '/shiju/zhuyu1/', '/shiju/jingying/', '/shiju/junxiu/',
                '/shiju/ganlu/', '/shiju/muyu1/', '/shiju/yaozhu/', '/shiju/qionglou/', '/shiju/gucha/',
                '/shiju/canfu/', '/shiju/choumei/', '/shiju/muli/', '/shiju/yusi/', '/shiju/hangongqiu/',
                '/shiju/chunni/', '/shiju/jianxia/', '/shiju/hualiang/', '/shiju/tingzhou/', '/shiju/xinqin/',
                '/shiju/chanming/', '/shiju/heshu/', '/shiju/hanqi/', '/shiju/chouyun/', '/shiju/youyu2/',
                '/shiju/yuwang1/', '/shiju/yuqiu/', '/shiju/shanshi/', '/shiju/shuisheng/', '/shiju/hanyu/',
                '/shiju/dengxian1/', '/shiju/lingcao/', '/shiju/zihua/', '/shiju/zhonglou/', '/shiju/gulou/',
                '/shiju/benchi/', '/shiju/huangmei/', '/shiju/nitu/', '/shiju/lanman/', '/shiju/wushu/',
                '/shiju/huoyan/', '/shiju/lingchen/', '/shiju/shanse/', '/shiju/shuise/', '/shiju/wangxiang/',
                '/shiju/rongyao/', '/shiju/tianting/', '/shiju/liusi/', '/shiju/baiou1/', '/shiju/jianning/',
                '/shiju/fengxianhua/', '/shiju/zhenhan/', '/shiju/jingnian/', '/shiju/huangyan/', '/shiju/rugu/',
                '/shiju/liaoluo/', '/shiju/gudan/', '/shiju/shuailuo/', '/shiju/fuqi/', '/shiju/pengyou/',
                '/shiju/tonghua/', '/shiju/yinhan1/', '/shiju/lvyin/', '/shiju/xinchun/', '/shiju/zhongzhu/',
                '/shiju/meijing/', '/shiju/liangchenmeijing/', '/shiju/fengnian1/', '/shiju/jinque/', '/shiju/huaxia/',
                '/shiju/caiye/', '/shiju/jicaihua/', '/shiju/cuiwei/', '/shiju/zhuzhang/', '/shiju/naikan/',
                '/shiju/rennai/', '/shiju/xiaochou/', '/shiju/zijin/', '/shiju/foxiang/', '/shiju/hanghai/',
                '/shiju/jidu/', '/shiju/dongliu/', '/shiju/qiushuang/', '/shiju/fengsheng1/', '/shiju/fengfu/',
                '/shiju/yueguang/', '/shiju/zhuanglie/', '/shiju/zhengyi1/', '/shiju/songhua1/', '/shiju/lingqi/',
                '/shiju/conghui/', '/shiju/mingda/', '/shiju/zhihui/', '/shiju/huanjian/', '/shiju/xiaosheng/',
                '/shiju/shuye/', '/shiju/pingwu/', '/shiju/liangbin/', '/shiju/chuilei/', '/shiju/kuqi/',
                '/shiju/fulu/', '/shiju/huashen/', '/shiju/tianqian1/', '/shiju/shichen/', '/shiju/kuaile/',
                '/shiju/xianxia/', '/shiju/yedu/', '/shiju/zhouchuan/', '/shiju/yangfan/', '/shiju/fuqin1/',
                '/shiju/suoyi/', '/shiju/huajian/', '/shiju/shijian2/', '/shiju/cuiling/', '/shiju/laohu/',
                '/shiju/leilei/', '/shiju/tangtang/', '/shiju/xiangxiang/', '/shiju/qiye/', '/shiju/caineng/',
                '/shiju/xueshi/', '/shiju/ermu/', '/shiju/shouzu/', '/shiju/shiting/', '/shiju/jianwen/',
                '/shiju/longzhongniao/', '/shiju/haoshi/', '/shiju/dahe/', '/shiju/jiushi1/', '/shiju/gaoyang/',
                '/shiju/qingpiao/', '/shiju/huoda/', '/shiju/chicheng/', '/shiju/wanghuai/', '/shiju/shengui/',
                '/shiju/tiandeng/', '/shiju/yuanqi/', '/shiju/dafang/', '/shiju/aizeng/', '/shiju/haowu/',
                '/shiju/mingzhe/', '/shiju/quanjiu/', '/shiju/chunpu/', '/shiju/jiajie/', '/shiju/yanhuo1/',
                '/shiju/yanyan1/', '/shiju/kongkuang/', '/shiju/tiancai/', '/shiju/miluojiang/', '/shiju/shanglinyuan/',
                '/shiju/mingguandian/', '/shiju/xianshua/', '/shiju/bainiao/', '/shiju/bian1/', '/shiju/jice/',
                '/shiju/chimu/', '/shiju/tianma1/', '/shiju/changye/', '/shiju/biguan/', '/shiju/shengming1/',
                '/shiju/sheren/', '/shiju/lianmian/', '/shiju/tuanshan/', '/shiju/nanfei/', '/shiju/beiyan/',
                '/shiju/caoshu/', '/shiju/shufa/', '/shiju/kaishu/', '/shiju/xiaokai/', '/shiju/fuxu/',
                '/shiju/luowei/', '/shiju/duxing/', '/shiju/canmeng/', '/shiju/lingluan/', '/shiju/lingluan1/',
                '/shiju/bumian/', '/shiju/buji/', '/shiju/chaoqun/', '/shiju/xiangdang/', '/shiju/chaoting/',
                '/shiju/daru/', '/shiju/fenming/', '/shiju/rongren/', '/shiju/kuanrong/', '/shiju/qiliang1/',
                '/shiju/duliang/', '/shiju/wusong/', '/shiju/tengman/', '/shiju/xinchang/', '/shiju/longzhong/',
                '/shiju/chuilao/', '/shiju/changduan/', '/shiju/qiangjiao/', '/shiju/duwang/', '/shiju/langji1/',
                '/shiju/qinqi/', '/shiju/shuhua/', '/shiju/chuxue/', '/shiju/cijiuyingxin/', '/shiju/qingbai/',
                '/shiju/zhuangding/', '/shiju/jisuan/', '/shiju/qiantu/', '/shiju/xiwang/', '/shiju/yijin/',
                '/shiju/bianhua/', '/shiju/wujin/', '/shiju/taiwan/', '/shiju/binglang/', '/shiju/zuxun/',
                '/shiju/yingwuzhou/', '/shiju/xiansan/', '/shiju/xinren1/', '/shiju/huadian/', '/shiju/huilan/',
                '/shiju/saiwai/', '/shiju/sifu/', '/shiju/zhuxian/', '/shiju/shuangshuang/', '/shiju/zican/',
                '/shiju/jimu/', '/shiju/manmu/', '/shiju/yuanwang/', '/shiju/yuanwang1/', '/shiju/yuanwang2/',
                '/shiju/mengduan/', '/shiju/yingou/', '/shiju/wanyue/', '/shiju/hexiang/', '/shiju/lanxin/',
                '/shiju/jinlan/', '/shiju/tongxue/', '/dianji/shijing/shiju/', '/dianji/daodejing/shiju/',
                '/dianji/lunyu/shiju/', '/dianji/shiji/shiju/', '/dianji/zizhitongjian/shiju/',
                '/dianji/shishuoxinyu/shiju/', '/dianji/caigentan/shiju/', '/dianji/hanfeizi/shiju/',
                '/dianji/zengguangxianwen/shiju/', '/dianji/chuanxilu/shiju/', '/dianji/liji/shiju/',
                '/dianji/chajing/shiju/', '/dianji/shangjunshu/shiju/', '/dianji/wenzi/shiju/',
                '/dianji/mingxianji/shiju/', '/novel/hongloumeng/shiju/', '/novel/guanchangxianxingji/shiju/',
                '/novel/xingshihengyan/shiju/']
        for url in urls:
            current_url = 'https://www.gushicimingju.com' + url
            yield scrapy.Request(method='GET', url=current_url, callback=self.parse_poem_quote,
                                 headers=self.headers, meta={'proxy': self.proxy_url})

    def parse_item(self, response):
        poem_quote_url = response.xpath(
            '//div[@class="main-content gushi-info"]//ul[@class="content-left left-4-col"]//a/@href').getall()
        for url in poem_quote_url:
            print(url)
            current_url = 'https://www.gushicimingju.com' + url
            yield scrapy.Request(url=current_url, callback=self.parse_poem_quote, headers=self.headers,
                                 meta={'proxy': self.proxy_url})

    def parse_quote_category(self, response):
        poem_quote = response.xpath(
            '//div[@class="main-content gushi-info"]//ul[@class="content-left left-4-col"]//a/text()').getall()
        print(poem_quote)
        items = list()
        for quote in poem_quote:
            print(quote)
            item = PoemQuoteCategoryItem()
            item['category_name'] = quote
            items.append(item)
        return items

    def parse_poem_quote(self, response):
        # pagination = response.xpath('//div[@class="main-content gushi-info"]//nav/ul/li[1]/span/text()').get()
        # self.quote_items.clear()
        # if pagination is not None:
        #     poem_count = pagination.split('共')[1]
        #     page = poem_count.split('页')[0]
        #     page_count = int(page) + 1
        #     for i in range(1, page_count):
        #         if i == 1:
        #             quotes = response.xpath(
        #                 '//div[@class="main-content gushi-info"]//div[@class="good-mingju main-data mingju-list"]')
        #             quotes_category = response.xpath(
        #                 '//div[@class="container position"]//div[@class="col-md-12"]/a[3]/text()').get()
        #             for item in quotes:
        #                 quote = PoemQuoteItem()
        #                 quote['poem_quote'] = item.xpath('.//span[2]//a/text()').get()
        #                 quote['poet_name'] = item.xpath('.//span[4]//a/text()').get()
        #                 quote['poem_title'] = item.xpath('.//span[5]/a/text()').get()
        #                 quote['quote_category'] = quotes_category
        #                 self.quote_items.append(quote)
        #         else:
        #             url = response.url + 'page' + str(i)
        #             yield scrapy.Request(url=url, headers=self.headers, meta={'proxy': self.proxy_url},
        #                                  callback=self.parse_poem_quote_page)
        # else:
        quote_items = list()
        quotes = response.xpath(
            '//div[@class="main-content gushi-info"]//div[@class="good-mingju main-data mingju-list"]')
        quotes_category = response.xpath(
            '//div[@class="container position"]//div[@class="col-md-12"]/a[3]/text()').get()
        for item in quotes:
            quote = PoemQuoteItem()
            quote['poem_quote'] = item.xpath('.//span[2]//a/text()').get()
            quote['poet_name'] = item.xpath('.//span[4]//a/text()').get()
            quote['poem_title'] = item.xpath('.//span[5]/a/text()').get()
            quote['quote_category'] = quotes_category
            quote_items.append(quote)
        # print(quote_items)
        return quote_items

    def parse_poem_quote_page(self, response):
        quotes = response.xpath(
            '//div[@class="main-content gushi-info"]//div[@class="good-mingju main-data mingju-list"]')
        quotes_category = response.xpath(
            '//div[@class="container position"]//div[@class="col-md-12"]/a[3]/text()').get()
        quote_items = list()
        for item in quotes:
            quote = PoemQuoteItem()
            quote['poem_quote'] = item.xpath('.//span[2]//a/text()').get()
            quote['poet_name'] = item.xpath('.//span[4]//a/text()').get()
            quote['poem_title'] = item.xpath('.//span[5]/a/text()').get()
            quote['quote_category'] = quotes_category
            quote_items.append(quote)
